-- Authoritative feature-owned executable suite list.
return {
    { name = "plugin and assets", path = "contract/assets.lua" },
    { name = "game rules", path = "unit/solvable_deals.lua" },
    { name = "game rules", path = "integration/deadlock.lua" },
    { name = "scoring and selection", path = "unit/scoring.lua" },
    { name = "scoring and selection", path = "unit/penalties.lua" },
    { name = "scoring and selection", path = "unit/combo_and_selection.lua" },
    { name = "persistence", path = "integration/persistence.lua" },
    { name = "lifetime stats", path = "integration/win_and_stats.lua" },
    { name = "board widget", path = "widget/board_geometry.lua" },
    { name = "board widget", path = "widget/board_paint.lua" },
    { name = "board widget", path = "widget/board_updates.lua" },
    { name = "picker widget", path = "widget/picker_grid.lua" },
    { name = "picker widget", path = "widget/picker_cards.lua" },
    { name = "picker widget", path = "widget/help.lua" },
    { name = "picker widget", path = "widget/picker_stats.lua" },
    { name = "picker widget", path = "widget/picker_paging.lua" },
    { name = "layout contracts", path = "contract/layout_registry.lua" },
    { name = "layout contracts", path = "contract/layout_spider.lua" },
    { name = "layout contracts", path = "contract/layout_bridge.lua" },
    { name = "layout contracts", path = "contract/layout_ziggurat.lua" },
    { name = "layout contracts", path = "contract/layout_cloud.lua" },
    { name = "layout contracts", path = "contract/layout_tictactoe.lua" },
    { name = "layout contracts", path = "contract/layout_red_dragon.lua" },
    { name = "layout contracts", path = "contract/layout_overpass.lua" },
    { name = "layout contracts", path = "contract/layout_pyramid.lua" },
    { name = "layout contracts", path = "contract/layout_confounding.lua" },
    { name = "layout contracts", path = "contract/layout_taipei.lua" },
    { name = "layout contracts", path = "contract/layout_crab.lua" },
    { name = "layout contracts", path = "contract/layout_zodiac.lua" },
    { name = "layout scores", path = "contract/layout_scores.lua" },
    { name = "gameplay", path = "integration/gameplay.lua" },
    { name = "gameplay", path = "integration/interaction_features.lua" },
    { name = "game lifecycle", path = "integration/game_lifecycle.lua" },
    { name = "game lifecycle", path = "integration/awake_policy.lua" },
    { name = "controller boundaries", path = "integration/controller_modules.lua" },
    { name = "timer and pause", path = "integration/timer.lua" },
    { name = "timer and pause", path = "integration/pause.lua" },
    { name = "auto-solve", path = "integration/autosolve.lua" },
    { name = "auto-solve", path = "integration/autosolve_lock.lua" },
    { name = "chrome", path = "widget/chrome.lua" },
    { name = "chrome", path = "widget/responsive.lua" },
    { name = "chrome", path = "widget/stats_card.lua" },
    { name = "localization", path = "integration/localization.lua" },
    { name = "localization", path = "integration/locale_defaults.lua" },
    { name = "e-ink refresh", path = "integration/timer_refresh.lua" },
    { name = "e-ink refresh", path = "widget/lower_chrome.lua" },
    { name = "e-ink refresh", path = "integration/full_refresh.lua" },
    { name = "e-ink refresh", path = "integration/refresh_batching.lua" },
    { name = "e-ink refresh", path = "integration/render_safety.lua" },
}
